// app/(dashboard)/handover/page.tsx
// Shift Handover Generator — one-click structured handover report

'use client';

import React, { useState } from 'react';
import { useAuthStore } from '@/lib/store/auth';
import { useShiftHandover, SHIFTS, type HandoverReport, type HandoverSection } from '@/lib/handover/shift-handover-hooks';
import { RoleGuard, openPrintWindow } from '@/components/ui/shared';

const SEV_STYLES: Record<string, { bg: string; border: string; title: string }> = {
  critical: { bg: 'bg-red-50', border: 'border-l-4 border-l-red-500', title: 'text-red-700' },
  warning: { bg: 'bg-amber-50', border: 'border-l-4 border-l-amber-400', title: 'text-amber-700' },
  info: { bg: 'bg-blue-50', border: 'border-l-4 border-l-blue-400', title: 'text-blue-700' },
  normal: { bg: 'bg-gray-50', border: 'border-l-4 border-l-gray-300', title: 'text-gray-700' },
};

function HandoverView({ report }: { report: HandoverReport }) {
  const shiftLabel = SHIFTS[report.shiftType]?.label || report.shiftType;
  const dateLabel = new Date(report.shiftStart).toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' });

  const printHandover = () => {
    const sectionsHtml = report.sections.map(s => {
      const sevColor = s.severity === 'critical' ? '#dc2626' : s.severity === 'warning' ? '#d97706' : s.severity === 'info' ? '#2563eb' : '#6b7280';
      const items = s.items.map(item =>
        `<div style="padding:6px 0;border-bottom:1px solid #f1f5f9;font-size:12px">
          ${item.patientName ? `<b>${item.patientName}</b>${item.bedLabel ? ` <span style="color:#6b7280">(Bed ${item.bedLabel})</span>` : ''}: ` : ''}${item.detail}</div>`
      ).join('');
      return `<div style="margin-bottom:16px;border-left:4px solid ${sevColor};padding-left:12px">
        <h3 style="font-size:13px;font-weight:700;color:${sevColor};margin:0 0 8px">${s.emoji} ${s.title} (${s.items.length})</h3>${items}</div>`;
    }).join('');

    openPrintWindow(`<div style="max-width:700px;margin:0 auto;font-family:Segoe UI,Arial;color:#1a1a1a">
      <div style="text-align:center;border-bottom:3px solid #1e40af;padding-bottom:10px;margin-bottom:16px">
        <div style="font-size:16px;font-weight:700;color:#1e40af">${report.centreName}</div>
        <div style="font-size:14px;font-weight:700;margin-top:6px">SHIFT HANDOVER REPORT</div>
        <div style="font-size:11px;color:#6b7280">${shiftLabel} &middot; ${dateLabel}</div></div>
      <div style="display:flex;gap:10px;margin-bottom:16px;flex-wrap:wrap">
        <div style="flex:1;background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:8px;text-align:center"><div style="font-size:18px;font-weight:800">${report.stats.totalAdmitted}</div><div style="font-size:9px;color:#64748b">Admitted</div></div>
        <div style="flex:1;background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:8px;text-align:center"><div style="font-size:18px;font-weight:800;color:#dc2626">${report.stats.criticalPatients}</div><div style="font-size:9px;color:#dc2626">Critical</div></div>
        <div style="flex:1;background:#fffbeb;border:1px solid #fde68a;border-radius:8px;padding:8px;text-align:center"><div style="font-size:18px;font-weight:800;color:#d97706">${report.stats.newAdmissions}</div><div style="font-size:9px;color:#d97706">New Adm</div></div>
        <div style="flex:1;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:8px;text-align:center"><div style="font-size:18px;font-weight:800;color:#16a34a">${report.stats.discharges}</div><div style="font-size:9px;color:#16a34a">Discharged</div></div>
        <div style="flex:1;background:#eff6ff;border:1px solid #bfdbfe;border-radius:8px;padding:8px;text-align:center"><div style="font-size:18px;font-weight:800;color:#2563eb">${report.stats.pendingActions}</div><div style="font-size:9px;color:#2563eb">Pending</div></div></div>
      ${sectionsHtml}
      <div style="margin-top:24px;padding-top:10px;border-top:1px solid #e2e8f0;display:flex;justify-content:space-between;font-size:10px;color:#94a3b8"><span>Generated by: ${report.generatedBy}</span><span>${new Date(report.generatedAt).toLocaleString('en-IN')}</span></div>
      <div style="margin-top:40px;display:flex;gap:40px"><div style="flex:1;border-top:1px solid #333;padding-top:4px;font-size:10px;text-align:center">Outgoing Nurse Signature</div><div style="flex:1;border-top:1px solid #333;padding-top:4px;font-size:10px;text-align:center">Incoming Nurse Signature</div></div></div>`);
  };

  return (
    <div>
      <div className="flex items-center justify-between mb-4">
        <div>
          <h2 className="text-lg font-bold text-gray-900">Shift Handover Report</h2>
          <p className="text-xs text-gray-500">{shiftLabel} · {dateLabel} · Generated by {report.generatedBy}</p>
        </div>
        <button onClick={printHandover} className="px-4 py-2 bg-teal-600 text-white text-xs font-medium rounded-lg hover:bg-teal-700">🖨️ Print</button>
      </div>

      <div className="grid grid-cols-5 gap-3 mb-6">
        <div className="bg-white rounded-xl border p-4 text-center"><div className="text-2xl font-black text-gray-900">{report.stats.totalAdmitted}</div><div className="text-[10px] text-gray-500">Admitted</div></div>
        <div className="bg-red-50 rounded-xl border border-red-200 p-4 text-center"><div className="text-2xl font-black text-red-600">{report.stats.criticalPatients}</div><div className="text-[10px] text-red-600">Critical</div></div>
        <div className="bg-amber-50 rounded-xl border border-amber-200 p-4 text-center"><div className="text-2xl font-black text-amber-600">{report.stats.newAdmissions}</div><div className="text-[10px] text-amber-600">New Admissions</div></div>
        <div className="bg-green-50 rounded-xl border border-green-200 p-4 text-center"><div className="text-2xl font-black text-green-600">{report.stats.discharges}</div><div className="text-[10px] text-green-600">Discharges</div></div>
        <div className="bg-blue-50 rounded-xl border border-blue-200 p-4 text-center"><div className="text-2xl font-black text-blue-600">{report.stats.pendingActions}</div><div className="text-[10px] text-blue-600">Pending</div></div>
      </div>

      <div className="space-y-4">
        {report.sections.map((section, si) => {
          const style = SEV_STYLES[section.severity] || SEV_STYLES.normal;
          return (
            <div key={si} className={`${style.bg} ${style.border} rounded-lg p-4`}>
              <h3 className={`text-xs font-bold ${style.title} mb-3`}>{section.emoji} {section.title} ({section.items.length})</h3>
              <div className="space-y-2">
                {section.items.map((item, ii) => (
                  <div key={ii} className="flex items-start gap-2 text-xs">
                    <span className="text-gray-400 mt-0.5 shrink-0">•</span>
                    <div>
                      {item.patientName && <span className="font-semibold text-gray-800">{item.patientName}</span>}
                      {item.bedLabel && <span className="text-gray-500 ml-1">(Bed {item.bedLabel})</span>}
                      {item.patientName && ': '}
                      <span className="text-gray-600">{item.detail}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          );
        })}
      </div>
      <div className="mt-6 text-center text-[10px] text-gray-400">Generated {new Date(report.generatedAt).toLocaleString('en-IN')}</div>
    </div>
  );
}

function HandoverInner() {
  const { staff } = useAuthStore();
  const centreId = useAuthStore(s => s.activeCentreId);
  const handover = useShiftHandover(centreId || null);
  const [selectedShift, setSelectedShift] = useState('night');
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);

  return (
    <div className="max-w-4xl mx-auto">
      <div className="flex items-center justify-between mb-6">
        <div><h1 className="text-xl font-bold text-gray-900">Shift Handover</h1>
          <p className="text-sm text-gray-500">Auto-generate structured handover report from clinical data</p></div>
      </div>

      {!handover.report && !handover.loading && (
        <div className="bg-white rounded-xl border p-6 mb-6">
          <h2 className="text-sm font-bold text-gray-800 mb-4">Generate Handover Report</h2>
          <div className="flex flex-wrap gap-4 items-end">
            <div>
              <label className="block text-xs font-medium text-gray-600 mb-1">Date</label>
              <input type="date" value={selectedDate} onChange={e => setSelectedDate(e.target.value)} className="px-3 py-2 border border-gray-200 rounded-lg text-sm" />
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-600 mb-1">Shift</label>
              <div className="flex gap-2">
                {Object.entries(SHIFTS).map(([key, s]) => (
                  <button key={key} onClick={() => setSelectedShift(key)}
                    className={`px-4 py-2 text-xs font-medium rounded-lg border transition-colors ${selectedShift === key ? 'bg-teal-600 text-white border-teal-600' : 'bg-white text-gray-600 border-gray-200'}`}>
                    {key === 'morning' ? '🌅' : key === 'evening' ? '🌇' : '🌙'} {s.label.split('(')[0].trim()}
                  </button>
                ))}
              </div>
            </div>
            <button onClick={() => handover.generate(selectedShift, staff?.full_name || 'Staff', selectedDate)}
              disabled={handover.loading}
              className="px-6 py-2 bg-teal-600 text-white text-sm font-medium rounded-lg hover:bg-teal-700 disabled:opacity-50">
              {handover.loading ? 'Generating...' : 'Generate Handover'}
            </button>
          </div>
          <p className="text-[10px] text-gray-400 mt-3">Scans admissions, labs, medications, rounds, alerts, and pending actions for the selected shift.</p>
        </div>
      )}

      {handover.loading && (
        <div className="text-center py-12">
          <div className="w-10 h-10 border-3 border-teal-600 border-t-transparent rounded-full animate-spin mx-auto mb-3" />
          <p className="text-sm text-gray-500">Scanning clinical data across all wards...</p>
        </div>
      )}

      {handover.report && !handover.loading && (
        <div>
          <button onClick={() => { /* Reset by generating empty */ }} className="text-xs text-gray-500 mb-3 hover:text-teal-600">← Generate another report</button>
          <HandoverView report={handover.report} />
        </div>
      )}

      {!handover.report && !handover.loading && (
        <div className="bg-gray-50 rounded-xl p-12 text-center">
          <div className="text-4xl mb-3">📋</div>
          <h3 className="text-sm font-semibold text-gray-700 mb-1">No handover report yet</h3>
          <p className="text-xs text-gray-400">Select shift and click Generate to create a structured handover document.</p>
        </div>
      )}
    </div>
  );
}

export default function HandoverPage() { return <RoleGuard><HandoverInner /></RoleGuard>; }
