// lib/reports/pdf-export.ts
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { ExcelSheet } from './excel-export';

const TEAL = [0, 128, 128] as const;
const DARK = [51, 51, 51] as const;
const GRAY = [128, 128, 128] as const;
const LIGHT_TEAL = [230, 245, 245] as const;

export function exportToPDF(sheets: ExcelSheet[], title: string) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  // Parse title for metadata: "Hospital — ReportName — Centre — Period"
  const parts = title.split(' — ');
  const reportName = parts[1] || title;
  const centreName = parts[2] || '';
  const period = parts[3] || '';

  sheets.forEach((sheet, sheetIdx) => {
    if (sheetIdx > 0) doc.addPage('a4', 'landscape');

    // ---- HEADER ----
    // Teal accent bar
    doc.setFillColor(...TEAL);
    doc.rect(0, 0, pageW, 2, 'F');

    // Hospital name
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(...TEAL);
    doc.text('Hospital', 14, 14);

    // Report title
    doc.setFontSize(11);
    doc.setTextColor(...DARK);
    doc.text(reportName + (sheets.length > 1 ? ' — ' + sheet.name : ''), 14, 21);

    // Centre + period (right-aligned)
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...GRAY);
    if (centreName) {
      doc.text(centreName, pageW - 14, 12, { align: 'right' });
    }
    if (period) {
      doc.text(period, pageW - 14, 17, { align: 'right' });
    }
    doc.text('Generated: ' + new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }), pageW - 14, 22, { align: 'right' });

    // Thin separator
    doc.setDrawColor(...TEAL);
    doc.setLineWidth(0.3);
    doc.line(14, 25, pageW - 14, 25);

    // ---- TABLE ----
    const head = [sheet.columns.map(c => c.label)];
    const body = sheet.data.map(row =>
      sheet.columns.map(c => {
        const val = row[c.key];
        if (val === null || val === undefined) return '';
        if (c.type === 'currency') {
          const n = parseFloat(val) || 0;
          return '\u20B9' + Math.round(n).toLocaleString('en-IN');
        }
        if (c.type === 'number') {
          const n = parseFloat(val) || 0;
          return Math.round(n).toLocaleString('en-IN');
        }
        if (c.type === 'percent') {
          return (parseFloat(val) || 0).toFixed(1) + '%';
        }
        return String(val);
      })
    );

    const colStyles: Record<number, { halign: 'left' | 'right' | 'center' }> = {};
    sheet.columns.forEach((c, i) => {
      if (c.type === 'currency' || c.type === 'number') {
        colStyles[i] = { halign: 'right' };
      } else if (c.type === 'percent') {
        colStyles[i] = { halign: 'center' };
      }
    });

    autoTable(doc, {
      startY: 28,
      head,
      body,
      margin: { left: 14, right: 14 },
      styles: {
        fontSize: 7.5,
        cellPadding: 2,
        lineColor: [220, 220, 220],
        lineWidth: 0.1,
        textColor: [...DARK] as [number, number, number],
      },
      headStyles: {
        fillColor: [...TEAL] as [number, number, number],
        textColor: [255, 255, 255] as [number, number, number],
        fontStyle: 'bold',
        fontSize: 7.5,
      },
      alternateRowStyles: {
        fillColor: [...LIGHT_TEAL] as [number, number, number],
      },
      columnStyles: colStyles,
      didDrawPage: () => {
        // Footer on every page
        const pageNum = (doc as any).internal.getCurrentPageInfo().pageNumber;
        const totalPages = (doc as any).internal.getNumberOfPages();
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7);
        doc.setTextColor(...GRAY);
        doc.text('Generated by HMIS', 14, pageH - 6);
        doc.text(`Page ${pageNum} of ${totalPages}`, pageW - 14, pageH - 6, { align: 'right' });

        // Bottom teal accent
        doc.setFillColor(...TEAL);
        doc.rect(0, pageH - 2, pageW, 2, 'F');
      },
    });
  });

  // Fix total page count on all pages (since we now know the total)
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    // Overdraw footer with correct total
    doc.setFillColor(255, 255, 255);
    doc.rect(pageW - 50, pageH - 10, 40, 5, 'F');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...GRAY);
    doc.text(`Page ${i} of ${totalPages}`, pageW - 14, pageH - 6, { align: 'right' });
  }

  // Extract filename from title
  const safeName = reportName.replace(/[^a-zA-Z0-9]/g, '_').replace(/_+/g, '_');
  doc.save(`Hospital_${safeName}_${new Date().toISOString().split('T')[0]}.pdf`);
}
