// HEALTH1 HMIS — BILLING MODULE TYPES

// Enums
export type EncounterType = 'OPD' | 'IPD' | 'ER' | 'DAYCARE';
export type PayorType = | 'SELF_PAY' | 'PMJAY' | 'CGHS' | 'TPA' | 'CORPORATE' | 'STAFF' | 'BPL' | 'OTHER_SCHEME';
export type EncounterStatus = | 'OPEN' | 'INTERIM_BILLED' | 'FINAL_BILLED' | 'DISCHARGED' | 'SETTLED' | 'CANCELLED';
export type LineItemStatus = 'ACTIVE' | 'CANCELLED' | 'REVERSED' | 'ADJUSTED';
export type InvoiceType = | 'OPD' | 'IPD_INTERIM' | 'IPD_FINAL' | 'PHARMACY' | 'LAB' | 'DISCHARGE' | 'CREDIT_NOTE' | 'ADVANCE_RECEIPT';
export type InvoiceStatus = | 'DRAFT' | 'GENERATED' | 'SENT' | 'PAID' | 'PARTIALLY_PAID' | 'CANCELLED' | 'CREDIT_NOTE_ISSUED';
export type PaymentMode = | 'CASH' | 'CARD' | 'UPI' | 'NEFT' | 'RTGS' | 'CHEQUE' | 'INSURANCE_SETTLEMENT' | 'WRITE_OFF' | 'ONLINE';
export type PaymentType = | 'COLLECTION' | 'ADVANCE' | 'DEPOSIT' | 'REFUND' | 'ADJUSTMENT' | 'WRITE_OFF';
export type PreAuthStatus = | 'DRAFT' | 'SUBMITTED' | 'QUERY' | 'APPROVED' | 'PARTIALLY_APPROVED' | 'REJECTED' | 'ENHANCEMENT_PENDING' | 'ENHANCED' | 'CANCELLED' | 'EXPIRED';
export type ClaimStatus = | 'DRAFT' | 'SUBMITTED' | 'UNDER_PROCESS' | 'QUERY_RAISED' | 'QUERY_RESPONDED' | 'APPROVED' | 'PARTIALLY_APPROVED' | 'SETTLED' | 'REJECTED' | 'APPEAL' | 'WRITTEN_OFF';
export type ServiceCategory = | 'CONSULTATION' | 'INVESTIGATION' | 'PROCEDURE' | 'SURGERY' | 'ROOM' | 'NURSING' | 'CONSUMABLE' | 'MEDICINE' | 'EQUIPMENT' | 'PACKAGE' | 'MISCELLANEOUS' | 'OT_CHARGE' | 'ICU_CHARGE' | 'AMBULANCE' | 'DIET' | 'PHYSIOTHERAPY' | 'BLOOD_BANK';
export type LineSource = | 'MANUAL' | 'ORDER' | 'PHARMACY' | 'LAB' | 'RADIOLOGY' | 'BED_CHARGE' | 'NURSING' | 'OT' | 'CONSUMABLE' | 'PACKAGE' | 'AUTO_CHARGE';
export type DiscountType = | 'PERCENTAGE' | 'FLAT' | 'PACKAGE' | 'STAFF' | 'SCHEME' | 'MANUAL';
export type PackageType = | 'SURGICAL' | 'MEDICAL' | 'DAYCARE' | 'MATERNITY' | 'PMJAY' | 'CGHS' | 'HEALTH_CHECKUP' | 'CUSTOM';
export type AuditAction = | 'CREATE' | 'UPDATE' | 'DELETE' | 'CANCEL' | 'VOID' | 'APPROVE' | 'REJECT' | 'SUBMIT' | 'LOCK' | 'UNLOCK' | 'PRINT' | 'REPRINT' | 'EXPORT';

// Master Tables
export interface TPAMaster { id: string; centre_id: string; tpa_name: string; tpa_code: string; contact_person: string | null; email: string | null; phone: string | null; address: string | null; portal_url: string | null; settlement_tat_days: number; is_active: boolean; created_at: string; updated_at: string; }
export interface InsuranceCompany { id: string; centre_id: string; company_name: string; company_code: string; company_type: string; tpa_id: string | null; tpa?: TPAMaster; contact_info: Record<string, any>; empanelment_number: string | null; empanelment_valid_till: string | null; rohini_code: string | null; is_cashless: boolean; is_active: boolean; created_at: string; updated_at: string; }
export interface ServiceMaster { id: string; centre_id: string; service_code: string; service_name: string; department: string; service_category: ServiceCategory; base_rate: number; gst_applicable: boolean; gst_percentage: number; hsn_sac_code: string | null; is_payable_to_doctor: boolean; doctor_payout_type: string | null; is_active: boolean; effective_from: string; effective_to: string | null; sort_order: number; created_at: string; updated_at: string; }
export interface RateCard { id: string; centre_id: string; payor_type: PayorType; payor_id: string | null; service_master_id: string; service_master?: ServiceMaster; rate: number; discount_percentage: number; effective_from: string; effective_to: string | null; is_active: boolean; created_at: string; }
export interface BillingPackage { id: string; centre_id: string; package_code: string; package_name: string; package_type: PackageType; payor_type: PayorType; base_price: number; validity_days: number; inclusions: string[]; exclusions: string[]; room_category: string | null; max_room_days: number | null; pmjay_package_code: string | null; cghs_package_code: string | null; is_active: boolean; created_at: string; updated_at: string; package_inclusions?: PackageInclusion[]; }
export interface PackageInclusion { id: string; package_id: string; service_master_id: string | null; service_category: ServiceCategory | null; quantity_limit: number; amount_limit: number | null; notes: string | null; }
export interface BedChargeRule { id: string; centre_id: string; room_category: string; ward_type: string; charge_per_day: number; nursing_charge_per_day: number; service_charge_per_day: number; checkout_time: string; half_day_hours: number; payor_type: PayorType; is_active: boolean; effective_from: string; created_at: string; }
export interface DiscountScheme { id: string; centre_id: string; scheme_name: string; scheme_code: string; discount_type: DiscountType; discount_value: number | null; category_rules: Array<{ category: string; percentage: number }> | null; max_discount_amount: number | null; requires_approval: boolean; approval_authority: string | null; auto_apply: boolean; is_active: boolean; valid_from: string | null; valid_to: string | null; created_at: string; }

// Transactional Tables
export interface BillingEncounter { id: string; centre_id: string; patient_id: string; encounter_type: EncounterType; encounter_number: string; admission_id: string | null; bed_id: string | null; admitting_doctor_id: string | null; admission_date: string | null; expected_discharge_date: string | null; actual_discharge_date: string | null; appointment_id: string | null; consulting_doctor_id: string | null; visit_date: string | null; primary_payor_type: PayorType; primary_payor_id: string | null; insurance_policy_number: string | null; insurance_card_number: string | null; tpa_id: string | null; insurance_company_id: string | null; pre_auth_id: string | null; package_id: string | null; total_charges: number; total_discounts: number; total_tax: number; net_amount: number; total_paid: number; total_refunded: number; balance_due: number; insurance_approved_amount: number; insurance_settled_amount: number; patient_responsibility: number; status: EncounterStatus; billing_locked: boolean; notes: string | null; created_by: string; created_at: string; updated_at: string; patient_name?: string; patient_uhid?: string; patient_phone?: string; patient_gender?: string; patient_dob?: string; line_items?: BillingLineItem[]; payments?: BillingPayment[]; invoices?: BillingInvoice[]; pre_auth?: PreAuth; tpa?: TPAMaster; insurance_company?: InsuranceCompany; package?: BillingPackage; }
export interface BillingLineItem { id: string; encounter_id: string; centre_id: string; service_master_id: string | null; service_code: string; service_name: string; department: string; service_category: ServiceCategory; quantity: number; unit_rate: number; gross_amount: number; discount_type: DiscountType | null; discount_value: number; discount_amount: number; tax_percentage: number; tax_amount: number; net_amount: number; service_doctor_id: string | null; referring_doctor_id: string | null; ordering_doctor_id: string | null; source_type: LineSource; source_id: string | null; is_package_item: boolean; package_id: string | null; covered_by_package: boolean; is_covered_by_insurance: boolean; insurance_approved_amount: number | null; patient_share: number | null; co_pay_percentage: number | null; service_date: string; billed_date: string; status: LineItemStatus; cancel_reason: string | null; cancelled_by: string | null; cancelled_at: string | null; payout_processed: boolean; payout_cycle_id: string | null; created_by: string; created_at: string; updated_at: string; service_doctor_name?: string; referring_doctor_name?: string; }
export interface BillingInvoice { id: string; encounter_id: string; centre_id: string; patient_id: string; invoice_number: string; invoice_type: InvoiceType; invoice_date: string; subtotal: number; total_discount: number; total_tax: number; grand_total: number; amount_paid: number; balance_due: number; insurance_share: number; patient_share: number; corporate_share: number; discount_authorized_by: string | null; discount_reason: string | null; pdf_url: string | null; pdf_generated_at: string | null; status: InvoiceStatus; created_by: string; created_at: string; updated_at: string; line_items?: BillingLineItem[]; }
export interface BillingPayment { id: string; encounter_id: string; invoice_id: string | null; centre_id: string; patient_id: string; receipt_number: string; payment_date: string; amount: number; payment_mode: PaymentMode; payment_reference: string | null; card_last_four: string | null; upi_id: string | null; bank_name: string | null; claim_id: string | null; settlement_reference: string | null; utr_number: string | null; payment_type: PaymentType; is_advance: boolean; advance_adjusted_amount: number; advance_balance: number; status: string; void_reason: string | null; voided_by: string | null; voided_at: string | null; created_by: string; created_at: string; }
export interface PreAuth { id: string; encounter_id: string; centre_id: string; patient_id: string; pre_auth_number: string | null; insurance_company_id: string; tpa_id: string | null; policy_number: string; member_id: string | null; diagnosis_codes: Array<{ code: string; description: string }>; procedure_codes: Array<{ code: string; description: string }> | null; treating_doctor_id: string | null; clinical_notes: string | null; requested_amount: number; requested_stay_days: number | null; request_date: string; approved_amount: number | null; approved_stay_days: number | null; approved_procedures: any[] | null; approval_date: string | null; approval_reference: string | null; enhancement_requested: boolean; enhancement_amount: number | null; enhancement_approved_amount: number | null; enhancement_date: string | null; enhancement_reference: string | null; documents: Array<{ type: string; url: string; uploaded_at: string }>; status: PreAuthStatus; rejection_reason: string | null; query_details: string | null; query_response: string | null; submitted_at: string | null; first_response_at: string | null; tat_hours: number | null; pmjay_claim_id: string | null; pmjay_pre_auth_id: string | null; pmjay_package_code: string | null; pmjay_package_name: string | null; created_by: string; created_at: string; updated_at: string; insurance_company?: InsuranceCompany; tpa?: TPAMaster; treating_doctor_name?: string; }
export interface InsuranceClaim { id: string; encounter_id: string; pre_auth_id: string | null; centre_id: string; patient_id: string; claim_number: string; insurance_company_id: string; tpa_id: string | null; claimed_amount: number; approved_amount: number | null; settled_amount: number | null; deduction_amount: number; tds_amount: number; net_received: number | null; patient_liability: number | null; deduction_details: Array<{ reason: string; amount: number }>; claim_submission_date: string | null; claim_approval_date: string | null; settlement_date: string | null; payment_received_date: string | null; settlement_utr: string | null; settlement_reference: string | null; tpa_claim_number: string | null; documents: Array<{ type: string; url: string; uploaded_at: string }>; pmjay_claim_id: string | null; pmjay_status: string | null; status: ClaimStatus; query_details: Array<{ date: string; query: string; response: string | null; response_date: string | null; }>; submission_to_settlement_days: number | null; aging_bucket: string | null; created_by: string; created_at: string; updated_at: string; insurance_company?: InsuranceCompany; tpa?: TPAMaster; encounter?: BillingEncounter; }
export interface CreditNote { id: string; original_invoice_id: string; credit_note_number: string; centre_id: string; patient_id: string; amount: number; reason: string; line_items: Array<{ line_item_id: string; amount: number; reason: string }>; refund_mode: PaymentMode | null; refund_reference: string | null; refund_processed: boolean; refund_processed_at: string | null; approved_by: string | null; approved_at: string | null; status: string; created_by: string; created_at: string; }
export interface BillingAuditLog { id: string; entity_type: string; entity_id: string; action: AuditAction; old_values: Record<string, any> | null; new_values: Record<string, any> | null; ip_address: string | null; user_agent: string | null; performed_by: string; performed_at: string; }

// UI / Form Types
export interface AddLineItemForm { service_master_id: string; quantity: number; unit_rate: number; service_doctor_id?: string; referring_doctor_id?: string; discount_type?: DiscountType; discount_value?: number; notes?: string; }
export interface RecordPaymentForm { amount: number; payment_mode: PaymentMode; payment_type: PaymentType; payment_reference?: string; card_last_four?: string; upi_id?: string; bank_name?: string; is_advance?: boolean; }
export interface CreateEncounterForm { patient_id: string; encounter_type: EncounterType; primary_payor_type: PayorType; primary_payor_id?: string; insurance_policy_number?: string; insurance_card_number?: string; tpa_id?: string; insurance_company_id?: string; package_id?: string; consulting_doctor_id?: string; admission_id?: string; bed_id?: string; admitting_doctor_id?: string; expected_discharge_date?: string; }
export interface PreAuthRequestForm { insurance_company_id: string; tpa_id?: string; policy_number: string; member_id?: string; diagnosis_codes: Array<{ code: string; description: string }>; procedure_codes?: Array<{ code: string; description: string }>; treating_doctor_id?: string; clinical_notes?: string; requested_amount: number; requested_stay_days?: number; pmjay_package_code?: string; }

// Dashboard / Analytics Types
export interface DailyCollectionSummary { collection_date: string; payment_mode: PaymentMode; txn_count: number; total_amount: number; }
export interface ClaimAgingSummary { aging_bucket: string; claim_count: number; total_amount: number; percentage: number; }
export interface TPAPerformance { tpa_id: string; tpa_name: string; avg_tat_days: number; approval_rate: number; deduction_rate: number; total_claims: number; total_claimed: number; total_settled: number; }
export interface RevenueSummary { department: string; service_category: ServiceCategory; gross_revenue: number; net_revenue: number; item_count: number; }
export interface BillingDashboardStats { today_collection: number; today_bills: number; pending_bills: number; insurance_pending_count: number; insurance_pending_amount: number; advance_balance: number; opd_count: number; ipd_active: number; }

// Constants
export const PAYOR_TYPE_LABELS: Record<PayorType, string> = { SELF_PAY: 'Self Pay', PMJAY: 'PMJAY (Ayushman Bharat)', CGHS: 'CGHS', TPA: 'TPA / Insurance', CORPORATE: 'Corporate', STAFF: 'Staff', BPL: 'BPL', OTHER_SCHEME: 'Other Scheme' };
export const ENCOUNTER_STATUS_COLORS: Record<EncounterStatus, string> = { OPEN: 'bg-blue-100 text-blue-700', INTERIM_BILLED: 'bg-yellow-100 text-yellow-700', FINAL_BILLED: 'bg-purple-100 text-purple-700', DISCHARGED: 'bg-green-100 text-green-700', SETTLED: 'bg-emerald-100 text-emerald-700', CANCELLED: 'bg-red-100 text-red-700' };
export const PREAUTH_STATUS_COLORS: Record<PreAuthStatus, string> = { DRAFT: 'bg-gray-100 text-gray-700', SUBMITTED: 'bg-blue-100 text-blue-700', QUERY: 'bg-orange-100 text-orange-700', APPROVED: 'bg-green-100 text-green-700', PARTIALLY_APPROVED: 'bg-yellow-100 text-yellow-700', REJECTED: 'bg-red-100 text-red-700', ENHANCEMENT_PENDING: 'bg-amber-100 text-amber-700', ENHANCED: 'bg-teal-100 text-teal-700', CANCELLED: 'bg-gray-100 text-gray-500', EXPIRED: 'bg-gray-100 text-gray-500' };
export const CLAIM_STATUS_COLORS: Record<ClaimStatus, string> = { DRAFT: 'bg-gray-100 text-gray-700', SUBMITTED: 'bg-blue-100 text-blue-700', UNDER_PROCESS: 'bg-indigo-100 text-indigo-700', QUERY_RAISED: 'bg-orange-100 text-orange-700', QUERY_RESPONDED: 'bg-amber-100 text-amber-700', APPROVED: 'bg-green-100 text-green-700', PARTIALLY_APPROVED: 'bg-yellow-100 text-yellow-700', SETTLED: 'bg-emerald-100 text-emerald-700', REJECTED: 'bg-red-100 text-red-700', APPEAL: 'bg-purple-100 text-purple-700', WRITTEN_OFF: 'bg-gray-100 text-gray-500' };
export const PAYMENT_MODE_LABELS: Record<PaymentMode, string> = { CASH: 'Cash', CARD: 'Card', UPI: 'UPI', NEFT: 'NEFT', RTGS: 'RTGS', CHEQUE: 'Cheque', INSURANCE_SETTLEMENT: 'Insurance Settlement', WRITE_OFF: 'Write Off', ONLINE: 'Online' };
export const SERVICE_CATEGORY_LABELS: Record<ServiceCategory, string> = { CONSULTATION: 'Consultation', INVESTIGATION: 'Investigation', PROCEDURE: 'Procedure', SURGERY: 'Surgery', ROOM: 'Room / Bed', NURSING: 'Nursing', CONSUMABLE: 'Consumable', MEDICINE: 'Medicine', EQUIPMENT: 'Equipment', PACKAGE: 'Package', MISCELLANEOUS: 'Miscellaneous', OT_CHARGE: 'OT Charge', ICU_CHARGE: 'ICU Charge', AMBULANCE: 'Ambulance', DIET: 'Diet', PHYSIOTHERAPY: 'Physiotherapy', BLOOD_BANK: 'Blood Bank' };
export const CENTRE_PREFIXES: Record<string, string> = { shilaj: 'H1-SH', modasa: 'H1-MD', gandhinagar: 'H1-GN', vastral: 'H1-VS', udaipur: 'H1-UD', sankalp: 'H1-SK' };
